import React from 'react'
import { FaSearch } from 'react-icons/fa'

export const OurData = [
  {
    id: 1,
    img: '	https://www.course-api.com/images/store/product-12.jpeg',
    icon: <FaSearch />,
    title: 'Modern Poster',
    price: 30.99,
    type: 'living',
    state: 'free',
    brand: 'liddy',
  },
  {
    id: 3,
    img: 'https://www.course-api.com/images/store/product-4.jpeg',
    icon: <FaSearch />,
    title: 'Armchair',
    price: 125.99,
    type: 'bedroom',
    state: 'free',
    brand: 'marcos',
  },
  {
    id: 4,
    img: '	https://www.course-api.com/images/store/product-16.jpeg',
    icon: <FaSearch />,
    title: 'Suede Armchair',
    price: 159.99,
    type: 'office',
    state: 'yes',
    brand: 'caressa',
  },
  {
    id: 5,
    img: 'https://www.course-api.com/images/store/product-9.jpeg',
    icon: <FaSearch />,
    title: 'Leather Chair',
    price: 200.99,
    type: 'bedroom',
    state: 'yes',
    brand: 'marcos',
  },
  {
    id: 6,
    img: 'https://www.course-api.com/images/store/product-6.jpeg',
    icon: <FaSearch />,
    title: 'Emperor Bed',
    price: 239.99,
    type: 'bedroom',
    state: 'free',
    brand: 'marcos',
  },
  {
    id: 7,
    img: 'https://www.course-api.com/images/store/product-1.jpeg',
    icon: <FaSearch />,
    title: 'Accent Chair',
    price: 259.99,
    type: 'office',
    state: 'free',
    brand: 'marcos',
  },
  {
    id: 8,
    img: '		https://www.course-api.com/images/store/product-13.jpeg',
    icon: <FaSearch />,
    title: 'Shelf',
    price: 309.99,
    type: 'living',
    state: 'yes',
    brand: 'ikea',
  },
  {
    id: 9,
    img: '	https://www.course-api.com/images/store/product-11.jpeg',
    icon: <FaSearch />,
    title: 'Modern Bookshelf',
    price: 319.99,
    type: 'kids',
    state: 'yes',
    brand: 'caressa',
  },
  {
    id: 10,
    img: '	https://www.course-api.com/images/store/product-8.jpeg',
    icon: <FaSearch />,
    title: 'High-Back Bench',
    price: 399.99,
    type: 'office',
    state: 'free',
    brand: 'ikea',
  },

  {
    id: 11,
    img: '	https://www.course-api.com/images/store/product-20.jpeg',
    icon: <FaSearch />,
    title: 'Wooden Desk',
    price: 400.99,
    type: 'office',
    state: 'yes',
    brand: 'ikea',
  },

  {
    id: 12,
    img: '	https://www.course-api.com/images/store/product-22.jpeg',
    icon: <FaSearch />,
    title: 'Dining Table',
    price: 429.99,
    type: 'dining',
    state: 'free',
    brand: 'liddy',
  },
  {
    id: 13,
    img: '	https://www.course-api.com/images/store/product-7.jpeg',
    icon: <FaSearch />,
    title: 'Entertainment Center',
    price: 599.99,
    type: 'living',
    state: 'free',
    brand: 'liddy',
  },
  {
    id: 14,
    img: '	https://www.course-api.com/images/store/product-17.jpeg',
    icon: <FaSearch />,
    title: 'Utopia Sofa',
    price: 799.99,
    type: 'living',
    state: 'yes',
    brand: 'liddy',
  },
  {
    id: 15,
    img: '	https://www.course-api.com/images/store/product-10.jpeg',
    icon: <FaSearch />,
    title: 'Leather Sofa',
    price: 999.99,
    type: 'office',
    state: 'yes',
    brand: 'marcos',
  },
  {
    id: 16,
    img: '	https://www.course-api.com/images/store/product-2.jpeg',
    icon: <FaSearch />,
    title: 'Albany Sectional',
    price: 1099.99,
    type: 'living',
    state: 'yes',
    brand: 'marcos',
  },
  {
    id: 17,
    img: '	https://www.course-api.com/images/store/product-14.jpeg',
    icon: <FaSearch />,
    title: 'Simple Chair',
    price: 1099.99,
    type: 'living',
    state: 'free',
    brand: 'marcos',
  },
  {
    id: 18,
    img: '	https://www.course-api.com/images/store/product-18.jpeg',
    icon: <FaSearch />,
    title: 'Vase Table',
    price: 1209.99,
    type: 'office',
    state: 'yes',
    brand: 'marcos',
  },
  {
    id: 19,
    img: '	https://www.course-api.com/images/store/product-15.jpeg',
    icon: <FaSearch />,
    title: 'Sofa Set',
    price: 1299.99,
    type: 'living',
    state: 'free',
    brand: 'marcos',
  },
  {
    id: 20,
    img: '	https://www.course-api.com/images/store/product-20.jpeg',
    icon: <FaSearch />,
    title: 'Wooden Desk',
    price: 234.99,
    type: 'b',
    state: 'free',
    brand: 'marcos',
  },
  {
    id: 21,
    img: '	https://www.course-api.com/images/store/product-22.jpeg',
    icon: <FaSearch />,
    title: 'Wooden table',
    price: 2349.99,
    type: 'kitchen',
    state: 'free',
    brand: 'marcos',
  },

  {
    id: 22,
    img: 'https://www.course-api.com/images/store/product-19.jpeg',
    icon: <FaSearch />,
    title: 'Wooden bed',
    price: 2500.99,
    type: 'bedroom',
    state: 'yes',
    brand: 'marcos',
  },
  {
    id: 23,
    img: 'https://www.course-api.com/images/store/product-3.jpeg',
    icon: <FaSearch />,
    title: 'Albany Table',
    price: 3099.9,
    type: 'kitchen',
    state: 'yes',
    brand: 'marcos',
  },
]
